name: Deploy to Jenkins

on:
  push:
    branches:
      - master

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Deployment
        run: |
          curl -X POST "http://${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}@${{ secrets.JENKINS_URL }}/job/deploy-mern/build?token=deploy123"